#!/usr/bin/env bash
#print using while loop and case statement

i=1
while [ $i -le 20 ]
do
	case $i in
		4)
		echo "bad luck from China"
		;;

		9)
		echo "bad luck from Japan"
		;;

		17)
		echo "bad luck from Italy"
		;;

		1 | 2 | 3 | 5 | 6 | 7 | 8 | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 18 | 19 | 20)
		echo $i
		;;
		
		*)
		echo "Invalid"
		;;
	esac
	(( i++ ))
done
