#!/usr/bin/env bash
#Write a Bash script that gives you information about the school file.
#    You must use if and, else (case is forbidden)
#    Your Bash script should check if the file exists and print:
#        if the file exists: school file exists
#        if the file does not exist: school file does not exist
#    If the file exists, print:
#	if the file is empty: school file is empty
#       if the file is not empty: school file is not empty
#       if the file is a regular file: school is a regular file
#       if the file is not a regular file: (nothing)
var="school"
if [ -e "$var" ]
then
	echo "$var file exists"
	if [ -s "$var" ]
	then 
		echo "$var file is not empty"
	else
		echo "$var file is empty"
	fi
	if [ -f "$var"]
	then
		echo "$var is a regular file"
	fi
else
	echo "$var file doesnot exist"
fi

